# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20171122_1042'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wished_by',
            field=models.ManyToManyField(related_name='wishlists', to='login.User'),
        ),
    ]
